#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("oqhra_android.Resource", IsApplication=true)]

namespace oqhra_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int RaceTracks = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int choosebet = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int currentstandings = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int explorebets = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int frontpage = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int horsemen = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int racebreed = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int racedistance = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int racegrade = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int raceresults = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int racesex = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int rprofs = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int savedrunstable = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int shopatt = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int stakescourses = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int upcoming = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_bobmoore = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_business = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_home = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back_lazye = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back_markel = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back_racehorseplace = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int back_yearsley = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backbtn_black = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int biggreybutton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bluebutton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bobmoore_iphone = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int calendar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int close = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int default_splash = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int exclaim = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int greybutton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int home_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int hp_iphone = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_tabs_cal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_tabs_home = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_tabs_news = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_tabs_race = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int launcher = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int news = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rightarrow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int silks = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int tableshape = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int uiglassbutton = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0700be
			public const int VideoLayout = 2131165374;
			
			// aapt resource value: 0x7f07008f
			public const int btnAge = 2131165327;
			
			// aapt resource value: 0x7f070095
			public const int btnBreed = 2131165333;
			
			// aapt resource value: 0x7f070084
			public const int btnCalc = 2131165316;
			
			// aapt resource value: 0x7f07009a
			public const int btnCalculate = 2131165338;
			
			// aapt resource value: 0x7f0700bd
			public const int btnCalculator = 2131165373;
			
			// aapt resource value: 0x7f0700c0
			public const int btnClose = 2131165376;
			
			// aapt resource value: 0x7f070049
			public const int btnDate = 2131165257;
			
			// aapt resource value: 0x7f070048
			public const int btnDistance = 2131165256;
			
			// aapt resource value: 0x7f07009b
			public const int btnExplore = 2131165339;
			
			// aapt resource value: 0x7f07008c
			public const int btnGrade = 2131165324;
			
			// aapt resource value: 0x7f070045
			public const int btnHorses = 2131165253;
			
			// aapt resource value: 0x7f070050
			public const int btnInfo = 2131165264;
			
			// aapt resource value: 0x7f07003f
			public const int btnNextMonth = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int btnPrevMonth = 2131165245;
			
			// aapt resource value: 0x7f070086
			public const int btnProcess = 2131165318;
			
			// aapt resource value: 0x7f070089
			public const int btnRaceTrac = 2131165321;
			
			// aapt resource value: 0x7f070052
			public const int btnResults = 2131165266;
			
			// aapt resource value: 0x7f070092
			public const int btnSex = 2131165330;
			
			// aapt resource value: 0x7f070047
			public const int btnTimes = 2131165255;
			
			// aapt resource value: 0x7f07009c
			public const int btnTipSheet = 2131165340;
			
			// aapt resource value: 0x7f070046
			public const int btnTrack = 2131165254;
			
			// aapt resource value: 0x7f070051
			public const int btnUpcoming = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int btnVideos = 2131165267;
			
			// aapt resource value: 0x7f070090
			public const int editAge = 2131165328;
			
			// aapt resource value: 0x7f0700b6
			public const int editRace1 = 2131165366;
			
			// aapt resource value: 0x7f0700b8
			public const int editRace2 = 2131165368;
			
			// aapt resource value: 0x7f07007f
			public const int editRaceTime = 2131165311;
			
			// aapt resource value: 0x7f0700ba
			public const int editWager = 2131165370;
			
			// aapt resource value: 0x7f070040
			public const int imgAdvert = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int imgBack = 2131165250;
			
			// aapt resource value: 0x7f070099
			public const int linLay = 2131165337;
			
			// aapt resource value: 0x7f07004f
			public const int linLayButtons = 2131165263;
			
			// aapt resource value: 0x7f070044
			public const int linLayout = 2131165252;
			
			// aapt resource value: 0x7f0700ac
			public const int linearBetTextRow = 2131165356;
			
			// aapt resource value: 0x7f0700b5
			public const int linlayBets = 2131165365;
			
			// aapt resource value: 0x7f07009f
			public const int linlayInner1 = 2131165343;
			
			// aapt resource value: 0x7f07004a
			public const int listView = 2131165258;
			
			// aapt resource value: 0x7f070001
			public const int masterTable = 2131165185;
			
			// aapt resource value: 0x7f070083
			public const int relLayRow = 2131165315;
			
			// aapt resource value: 0x7f070000
			public const int relLayout = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int row0 = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int row1 = 2131165195;
			
			// aapt resource value: 0x7f07006b
			public const int row10 = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int row11 = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int row12 = 2131165293;
			
			// aapt resource value: 0x7f07006f
			public const int row13 = 2131165295;
			
			// aapt resource value: 0x7f070071
			public const int row14 = 2131165297;
			
			// aapt resource value: 0x7f070073
			public const int row15 = 2131165299;
			
			// aapt resource value: 0x7f070075
			public const int row16 = 2131165301;
			
			// aapt resource value: 0x7f07005c
			public const int row1a = 2131165276;
			
			// aapt resource value: 0x7f07005e
			public const int row1b = 2131165278;
			
			// aapt resource value: 0x7f070013
			public const int row2 = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int row3 = 2131165211;
			
			// aapt resource value: 0x7f070023
			public const int row4 = 2131165219;
			
			// aapt resource value: 0x7f07002b
			public const int row5 = 2131165227;
			
			// aapt resource value: 0x7f070033
			public const int row6 = 2131165235;
			
			// aapt resource value: 0x7f070065
			public const int row7 = 2131165285;
			
			// aapt resource value: 0x7f070067
			public const int row8 = 2131165287;
			
			// aapt resource value: 0x7f070069
			public const int row9 = 2131165289;
			
			// aapt resource value: 0x7f07004e
			public const int rowButtons = 2131165262;
			
			// aapt resource value: 0x7f070055
			public const int secondline = 2131165269;
			
			// aapt resource value: 0x7f07005a
			public const int shopping = 2131165274;
			
			// aapt resource value: 0x7f0700a8
			public const int spinnerBetType = 2131165352;
			
			// aapt resource value: 0x7f070096
			public const int spinnerBreed = 2131165334;
			
			// aapt resource value: 0x7f070098
			public const int spinnerDist = 2131165336;
			
			// aapt resource value: 0x7f07008d
			public const int spinnerGrade = 2131165325;
			
			// aapt resource value: 0x7f07007b
			public const int spinnerSelDist = 2131165307;
			
			// aapt resource value: 0x7f070093
			public const int spinnerSex = 2131165331;
			
			// aapt resource value: 0x7f07008a
			public const int spinnerTrack = 2131165322;
			
			// aapt resource value: 0x7f0700bf
			public const int surfaceView = 2131165375;
			
			// aapt resource value: 0x7f070056
			public const int tab1 = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int tab2 = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int tab3 = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int tab4 = 2131165273;
			
			// aapt resource value: 0x7f070002
			public const int table = 2131165186;
			
			// aapt resource value: 0x7f0700aa
			public const int tableBet = 2131165354;
			
			// aapt resource value: 0x7f07003b
			public const int tableBtns = 2131165243;
			
			// aapt resource value: 0x7f07004c
			public const int tableFB = 2131165260;
			
			// aapt resource value: 0x7f070080
			public const int tableRes = 2131165312;
			
			// aapt resource value: 0x7f070041
			public const int tableRow = 2131165249;
			
			// aapt resource value: 0x7f07003c
			public const int tableRowBtn = 2131165244;
			
			// aapt resource value: 0x7f070077
			public const int tableSpeedEntry = 2131165303;
			
			// aapt resource value: 0x7f070087
			public const int tableStake = 2131165319;
			
			// aapt resource value: 0x7f07009e
			public const int tableTop = 2131165342;
			
			// aapt resource value: 0x7f07005b
			public const int text1 = 2131165275;
			
			// aapt resource value: 0x7f07006e
			public const int text12 = 2131165294;
			
			// aapt resource value: 0x7f070070
			public const int text13 = 2131165296;
			
			// aapt resource value: 0x7f070072
			public const int text14 = 2131165298;
			
			// aapt resource value: 0x7f070074
			public const int text15 = 2131165300;
			
			// aapt resource value: 0x7f070076
			public const int text16 = 2131165302;
			
			// aapt resource value: 0x7f07005d
			public const int text1a = 2131165277;
			
			// aapt resource value: 0x7f07005f
			public const int text1b = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int text2 = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int text3 = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int text4 = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int text5 = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int text6 = 2131165284;
			
			// aapt resource value: 0x7f070066
			public const int text7 = 2131165286;
			
			// aapt resource value: 0x7f070068
			public const int text8 = 2131165288;
			
			// aapt resource value: 0x7f07006a
			public const int text9 = 2131165290;
			
			// aapt resource value: 0x7f0700a7
			public const int textBetType = 2131165351;
			
			// aapt resource value: 0x7f0700a9
			public const int textBlank = 2131165353;
			
			// aapt resource value: 0x7f0700af
			public const int textBlank1 = 2131165359;
			
			// aapt resource value: 0x7f0700b1
			public const int textBlank2 = 2131165361;
			
			// aapt resource value: 0x7f0700b7
			public const int textBlank3 = 2131165367;
			
			// aapt resource value: 0x7f0700b9
			public const int textBlank4 = 2131165369;
			
			// aapt resource value: 0x7f07000c
			public const int textDate1 = 2131165196;
			
			// aapt resource value: 0x7f070016
			public const int textDate10 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int textDate11 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int textDate12 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int textDate13 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int textDate14 = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int textDate15 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int textDate16 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int textDate17 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int textDate18 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int textDate19 = 2131165216;
			
			// aapt resource value: 0x7f07000d
			public const int textDate2 = 2131165197;
			
			// aapt resource value: 0x7f070021
			public const int textDate20 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int textDate21 = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int textDate22 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int textDate23 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int textDate24 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int textDate25 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int textDate26 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int textDate27 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int textDate28 = 2131165226;
			
			// aapt resource value: 0x7f07002c
			public const int textDate29 = 2131165228;
			
			// aapt resource value: 0x7f07000e
			public const int textDate3 = 2131165198;
			
			// aapt resource value: 0x7f07002d
			public const int textDate30 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int textDate31 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int textDate32 = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int textDate33 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int textDate34 = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int textDate35 = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int textDate36 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int textDate37 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int textDate38 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int textDate39 = 2131165239;
			
			// aapt resource value: 0x7f07000f
			public const int textDate4 = 2131165199;
			
			// aapt resource value: 0x7f070038
			public const int textDate40 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int textDate41 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int textDate42 = 2131165242;
			
			// aapt resource value: 0x7f070010
			public const int textDate5 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int textDate6 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int textDate7 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int textDate8 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int textDate9 = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int textFri = 2131165193;
			
			// aapt resource value: 0x7f0700a2
			public const int textInstruct1 = 2131165346;
			
			// aapt resource value: 0x7f0700a4
			public const int textInstruct2 = 2131165348;
			
			// aapt resource value: 0x7f0700ad
			public const int textLeftBlank = 2131165357;
			
			// aapt resource value: 0x7f070005
			public const int textMon = 2131165189;
			
			// aapt resource value: 0x7f07003e
			public const int textMonthYear = 2131165246;
			
			// aapt resource value: 0x7f0700ae
			public const int textRace1 = 2131165358;
			
			// aapt resource value: 0x7f0700b0
			public const int textRace2 = 2131165360;
			
			// aapt resource value: 0x7f07007e
			public const int textRaceTime = 2131165310;
			
			// aapt resource value: 0x7f07000a
			public const int textSat = 2131165194;
			
			// aapt resource value: 0x7f07007a
			public const int textSelDist = 2131165306;
			
			// aapt resource value: 0x7f070004
			public const int textSun = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int textThu = 2131165192;
			
			// aapt resource value: 0x7f070043
			public const int textTitle = 2131165251;
			
			// aapt resource value: 0x7f070006
			public const int textTue = 2131165190;
			
			// aapt resource value: 0x7f0700b2
			public const int textWager = 2131165362;
			
			// aapt resource value: 0x7f070007
			public const int textWed = 2131165191;
			
			// aapt resource value: 0x7f070054
			public const int topline = 2131165268;
			
			// aapt resource value: 0x7f0700a0
			public const int trBlank1 = 2131165344;
			
			// aapt resource value: 0x7f0700a5
			public const int trBlank2 = 2131165349;
			
			// aapt resource value: 0x7f0700b3
			public const int trBlank3 = 2131165363;
			
			// aapt resource value: 0x7f0700bb
			public const int trBlank4 = 2131165371;
			
			// aapt resource value: 0x7f07004d
			public const int webviewInfo = 2131165261;
			
			// aapt resource value: 0x7f0700c1
			public const int webviewer = 2131165377;
			
			// aapt resource value: 0x7f070081
			public const int widget103 = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int widget104 = 2131165314;
			
			// aapt resource value: 0x7f070085
			public const int widget105 = 2131165317;
			
			// aapt resource value: 0x7f070088
			public const int widget34 = 2131165320;
			
			// aapt resource value: 0x7f07008b
			public const int widget35 = 2131165323;
			
			// aapt resource value: 0x7f07008e
			public const int widget36 = 2131165326;
			
			// aapt resource value: 0x7f070091
			public const int widget37 = 2131165329;
			
			// aapt resource value: 0x7f070094
			public const int widget38 = 2131165332;
			
			// aapt resource value: 0x7f070097
			public const int widget39 = 2131165335;
			
			// aapt resource value: 0x7f07004b
			public const int widget51 = 2131165259;
			
			// aapt resource value: 0x7f07009d
			public const int widget57 = 2131165341;
			
			// aapt resource value: 0x7f0700a1
			public const int widget66 = 2131165345;
			
			// aapt resource value: 0x7f0700a3
			public const int widget67 = 2131165347;
			
			// aapt resource value: 0x7f0700a6
			public const int widget73 = 2131165350;
			
			// aapt resource value: 0x7f0700ab
			public const int widget81 = 2131165355;
			
			// aapt resource value: 0x7f0700b4
			public const int widget83 = 2131165364;
			
			// aapt resource value: 0x7f070078
			public const int widget94 = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int widget95 = 2131165305;
			
			// aapt resource value: 0x7f07007c
			public const int widget96 = 2131165308;
			
			// aapt resource value: 0x7f07007d
			public const int widget97 = 2131165309;
			
			// aapt resource value: 0x7f0700bc
			public const int widgt85 = 2131165372;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int advert_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int five_buttons = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fourbuttons = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listview_2lines = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listview_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main_original = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int shopping = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int speedindex = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int stakes = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int threebuttons = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int video = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int webview = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040010
			public const int ChooseBetTitle = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int ComingSoon = 2130968585;
			
			// aapt resource value: 0x7f040013
			public const int FM = 2130968595;
			
			// aapt resource value: 0x7f04000b
			public const int ForHorse = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int MainTitle = 2130968583;
			
			// aapt resource value: 0x7f040012
			public const int RP = 2130968594;
			
			// aapt resource value: 0x7f04000a
			public const int RaceRes = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int Tracks = 2130968584;
			
			// aapt resource value: 0x7f040014
			public const int WR = 2130968596;
			
			// aapt resource value: 0x7f040006
			public const int appname = 2130968582;
			
			// aapt resource value: 0x7f040011
			public const int cbintro = 2130968593;
			
			// aapt resource value: 0x7f040016
			public const int choosedist = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int choosedistbtn = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int dining = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int menu_calendar = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int menu_copyright = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int menu_home = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int menu_news = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int menu_quit = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int menu_stakes = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int profiles = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int savedruns = 2130968597;
			
			// aapt resource value: 0x7f040018
			public const int shopping = 2130968600;
			
			// aapt resource value: 0x7f04000d
			public const int speedind = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int standings = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int vids = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
